### PR TITLE
Fix segwit handling

### PR DESCRIPTION
**Pull request by dignifiedquire**
~~not ready yet, just for me to make comparison easier~~

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Tests are passing 🎉

**Comment by hsanjuan** [comment]
```

**Comment by hsanjuan** [comment]
Ingesting: 000000000000000000ac2a49162ec7c457212134e46ab24daa63e0fae949bd90:
```
failure putting to ipfs: dag/put: failed to read tx(530): failed to parse tx(181): failed to read all bytes(1391173309): unexpected EOF
```

With 000000000000000000d172ef46944db6127dbebe815664f26f37fef3e22fd65b:

```
 failure putting to ipfs: dag/put: failed to read tx(115): failed to parse tx(123): failed to read length: varint overflow: -5038015692040045288
```

**Comment by dignifiedquire** [comment]
at least the error handling works as expected

**Pull request merged**
