### PR TITLE
update go-test workflow

### PR DESCRIPTION
**Pull request by ipldbot**
update to https://github.com/ipld/.github/commit/738ae9ec7a27b6dddb266cccb6edfb17b418eb74

---
You can trigger a rebase by commenting `@ipldbot rebase`.

### CODE REVIEW

**Comment by marten-seemann** [comment]
CI failure was fixed by #12, so this should be ready to merge now.

**Comment by rvagg** [comment]
:thumbsup: but we should remove travis first I think

**Comment by marten-seemann** [comment]
@rvagg Who do we need to ping for that?

**Comment by rvagg** [comment]
probably me

**Comment by mvdan** [comment]
done, please rebase to fix the failures

**Comment by marten-seemann** [comment]
@ipldbot rebase

**Review by mvdan — APPROVED** [review]

**Comment by rvagg** [comment]
@marten-seemann did it rebase properly? the sequence here looks like there was a force-push _before_ your comment, but is that just the interface being inconsistent?

**Comment by marten-seemann** [comment]
It didn’t. There’s yet another permission issue here. We need an org-wide secret IPLDBOT_GITHUB_TOKEN so ipldbot can perform the rebase. I asked @vmx to add it.

**Pull request merged**
